include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
